"""demo demo

Revision ID: fb4fb0c6571
Revises: None
Create Date: 2016-12-27 22:49:50.168781

"""

# revision identifiers, used by Alembic.
revision = 'fb4fb0c6571'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
